// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: map.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tibia.Protobuf.Map {

  /// <summary>Holder for reflection information generated from map.proto</summary>
  public static partial class MapReflection {

    #region Descriptor
    /// <summary>File descriptor for map.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MapReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgltYXAucHJvdG8SEnRpYmlhLnByb3RvYnVmLm1hcBoMc2hhcmVkLnByb3Rv",
            "IpgCCgNNYXASJwoFYXJlYXMYASADKAsyGC50aWJpYS5wcm90b2J1Zi5tYXAu",
            "QXJlYRIlCgRucGNzGAIgAygLMhcudGliaWEucHJvdG9idWYubWFwLk5wYxIz",
            "Cg5yZXNvdXJjZV9maWxlcxgDIAMoCzIbLnRpYmlhLnByb3RvYnVmLm1hcC5N",
            "YXBGaWxlEkMKGHRvcF9sZWZ0X3RpbGVfY29vcmRpbmF0ZRgEIAEoCzIhLnRp",
            "YmlhLnByb3RvYnVmLnNoYXJlZC5Db29yZGluYXRlEkcKHGJvdHRvbV9yaWdo",
            "dF90aWxlX2Nvb3JkaW5hdGUYBSABKAsyIS50aWJpYS5wcm90b2J1Zi5zaGFy",
            "ZWQuQ29vcmRpbmF0ZSLSAQoEQXJlYRIPCgdhcmVhX2lkGAEgASgNEgwKBG5h",
            "bWUYAiABKAkSMAoJYXJlYV90eXBlGAMgASgOMh0udGliaWEucHJvdG9idWYu",
            "bWFwLkFSRUFfVFlQRRITCgtzdWJhcmVhX2lkcxgEIAMoDRI7ChBsYWJlbF9j",
            "b29yZGluYXRlGAUgASgLMiEudGliaWEucHJvdG9idWYuc2hhcmVkLkNvb3Jk",
            "aW5hdGUSGAoQcmVqZWN0X2RvbmF0aW9ucxgGIAEoCBINCgVhbGlhcxgHIAEo",
            "CSJjCgNOcGMSDAoEbmFtZRgBIAEoCRI6Cg90aWxlX2Nvb3JkaW5hdGUYAiAB",
            "KAsyIS50aWJpYS5wcm90b2J1Zi5zaGFyZWQuQ29vcmRpbmF0ZRISCgpzdWJh",
            "cmVhX2lkGAMgASgNIuYBCgdNYXBGaWxlEjQKCWZpbGVfdHlwZRgBIAEoDjIh",
            "LnRpYmlhLnByb3RvYnVmLm1hcC5NQVBfRklMRV9UWVBFEj4KE3RvcF9sZWZ0",
            "X2Nvb3JkaW5hdGUYAiABKAsyIS50aWJpYS5wcm90b2J1Zi5zaGFyZWQuQ29v",
            "cmRpbmF0ZRIRCglmaWxlX25hbWUYAyABKAkSFAoMZmllbGRzX3dpZHRoGAQg",
            "ASgNEhUKDWZpZWxkc19oZWlnaHQYBSABKA0SDwoHYXJlYV9pZBgGIAEoDRIU",
            "CgxzY2FsZV9mYWN0b3IYByABKAEqYgoNTUFQX0ZJTEVfVFlQRRIZChVNQVBf",
            "RklMRV9UWVBFX1NVQkFSRUEQABIbChdNQVBfRklMRV9UWVBFX1NBVEVMTElU",
            "RRABEhkKFU1BUF9GSUxFX1RZUEVfTUlOSU1BUBACKkoKCUFSRUFfVFlQRRIS",
            "Cg5BUkVBX1RZUEVfTk9ORRAAEhIKDkFSRUFfVFlQRV9BUkVBEAESFQoRQVJF",
            "QV9UWVBFX1NVQkFSRUEQAg=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Tibia.Protobuf.Shared.SharedReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Tibia.Protobuf.Map.MAP_FILE_TYPE), typeof(global::Tibia.Protobuf.Map.AREA_TYPE), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Tibia.Protobuf.Map.Map), global::Tibia.Protobuf.Map.Map.Parser, new[]{ "Areas", "Npcs", "ResourceFiles", "TopLeftTileCoordinate", "BottomRightTileCoordinate" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Tibia.Protobuf.Map.Area), global::Tibia.Protobuf.Map.Area.Parser, new[]{ "AreaId", "Name", "AreaType", "SubareaIds", "LabelCoordinate", "RejectDonations", "Alias" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Tibia.Protobuf.Map.Npc), global::Tibia.Protobuf.Map.Npc.Parser, new[]{ "Name", "TileCoordinate", "SubareaId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Tibia.Protobuf.Map.MapFile), global::Tibia.Protobuf.Map.MapFile.Parser, new[]{ "FileType", "TopLeftCoordinate", "FileName", "FieldsWidth", "FieldsHeight", "AreaId", "ScaleFactor" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum MAP_FILE_TYPE {
    [pbr::OriginalName("MAP_FILE_TYPE_SUBAREA")] Subarea = 0,
    [pbr::OriginalName("MAP_FILE_TYPE_SATELLITE")] Satellite = 1,
    [pbr::OriginalName("MAP_FILE_TYPE_MINIMAP")] Minimap = 2,
  }

  public enum AREA_TYPE {
    [pbr::OriginalName("AREA_TYPE_NONE")] None = 0,
    [pbr::OriginalName("AREA_TYPE_AREA")] Area = 1,
    [pbr::OriginalName("AREA_TYPE_SUBAREA")] Subarea = 2,
  }

  #endregion

  #region Messages
  public sealed partial class Map : pb::IMessage<Map>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Map> _parser = new pb::MessageParser<Map>(() => new Map());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Map> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tibia.Protobuf.Map.MapReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Map() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Map(Map other) : this() {
      areas_ = other.areas_.Clone();
      npcs_ = other.npcs_.Clone();
      resourceFiles_ = other.resourceFiles_.Clone();
      topLeftTileCoordinate_ = other.topLeftTileCoordinate_ != null ? other.topLeftTileCoordinate_.Clone() : null;
      bottomRightTileCoordinate_ = other.bottomRightTileCoordinate_ != null ? other.bottomRightTileCoordinate_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Map Clone() {
      return new Map(this);
    }

    /// <summary>Field number for the "areas" field.</summary>
    public const int AreasFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Tibia.Protobuf.Map.Area> _repeated_areas_codec
        = pb::FieldCodec.ForMessage(10, global::Tibia.Protobuf.Map.Area.Parser);
    private readonly pbc::RepeatedField<global::Tibia.Protobuf.Map.Area> areas_ = new pbc::RepeatedField<global::Tibia.Protobuf.Map.Area>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Tibia.Protobuf.Map.Area> Areas {
      get { return areas_; }
    }

    /// <summary>Field number for the "npcs" field.</summary>
    public const int NpcsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Tibia.Protobuf.Map.Npc> _repeated_npcs_codec
        = pb::FieldCodec.ForMessage(18, global::Tibia.Protobuf.Map.Npc.Parser);
    private readonly pbc::RepeatedField<global::Tibia.Protobuf.Map.Npc> npcs_ = new pbc::RepeatedField<global::Tibia.Protobuf.Map.Npc>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Tibia.Protobuf.Map.Npc> Npcs {
      get { return npcs_; }
    }

    /// <summary>Field number for the "resource_files" field.</summary>
    public const int ResourceFilesFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Tibia.Protobuf.Map.MapFile> _repeated_resourceFiles_codec
        = pb::FieldCodec.ForMessage(26, global::Tibia.Protobuf.Map.MapFile.Parser);
    private readonly pbc::RepeatedField<global::Tibia.Protobuf.Map.MapFile> resourceFiles_ = new pbc::RepeatedField<global::Tibia.Protobuf.Map.MapFile>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Tibia.Protobuf.Map.MapFile> ResourceFiles {
      get { return resourceFiles_; }
    }

    /// <summary>Field number for the "top_left_tile_coordinate" field.</summary>
    public const int TopLeftTileCoordinateFieldNumber = 4;
    private global::Tibia.Protobuf.Shared.Coordinate topLeftTileCoordinate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tibia.Protobuf.Shared.Coordinate TopLeftTileCoordinate {
      get { return topLeftTileCoordinate_; }
      set {
        topLeftTileCoordinate_ = value;
      }
    }

    /// <summary>Field number for the "bottom_right_tile_coordinate" field.</summary>
    public const int BottomRightTileCoordinateFieldNumber = 5;
    private global::Tibia.Protobuf.Shared.Coordinate bottomRightTileCoordinate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tibia.Protobuf.Shared.Coordinate BottomRightTileCoordinate {
      get { return bottomRightTileCoordinate_; }
      set {
        bottomRightTileCoordinate_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Map);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Map other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!areas_.Equals(other.areas_)) return false;
      if(!npcs_.Equals(other.npcs_)) return false;
      if(!resourceFiles_.Equals(other.resourceFiles_)) return false;
      if (!object.Equals(TopLeftTileCoordinate, other.TopLeftTileCoordinate)) return false;
      if (!object.Equals(BottomRightTileCoordinate, other.BottomRightTileCoordinate)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= areas_.GetHashCode();
      hash ^= npcs_.GetHashCode();
      hash ^= resourceFiles_.GetHashCode();
      if (topLeftTileCoordinate_ != null) hash ^= TopLeftTileCoordinate.GetHashCode();
      if (bottomRightTileCoordinate_ != null) hash ^= BottomRightTileCoordinate.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      areas_.WriteTo(output, _repeated_areas_codec);
      npcs_.WriteTo(output, _repeated_npcs_codec);
      resourceFiles_.WriteTo(output, _repeated_resourceFiles_codec);
      if (topLeftTileCoordinate_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(TopLeftTileCoordinate);
      }
      if (bottomRightTileCoordinate_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(BottomRightTileCoordinate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      areas_.WriteTo(ref output, _repeated_areas_codec);
      npcs_.WriteTo(ref output, _repeated_npcs_codec);
      resourceFiles_.WriteTo(ref output, _repeated_resourceFiles_codec);
      if (topLeftTileCoordinate_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(TopLeftTileCoordinate);
      }
      if (bottomRightTileCoordinate_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(BottomRightTileCoordinate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += areas_.CalculateSize(_repeated_areas_codec);
      size += npcs_.CalculateSize(_repeated_npcs_codec);
      size += resourceFiles_.CalculateSize(_repeated_resourceFiles_codec);
      if (topLeftTileCoordinate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TopLeftTileCoordinate);
      }
      if (bottomRightTileCoordinate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BottomRightTileCoordinate);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Map other) {
      if (other == null) {
        return;
      }
      areas_.Add(other.areas_);
      npcs_.Add(other.npcs_);
      resourceFiles_.Add(other.resourceFiles_);
      if (other.topLeftTileCoordinate_ != null) {
        if (topLeftTileCoordinate_ == null) {
          TopLeftTileCoordinate = new global::Tibia.Protobuf.Shared.Coordinate();
        }
        TopLeftTileCoordinate.MergeFrom(other.TopLeftTileCoordinate);
      }
      if (other.bottomRightTileCoordinate_ != null) {
        if (bottomRightTileCoordinate_ == null) {
          BottomRightTileCoordinate = new global::Tibia.Protobuf.Shared.Coordinate();
        }
        BottomRightTileCoordinate.MergeFrom(other.BottomRightTileCoordinate);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            areas_.AddEntriesFrom(input, _repeated_areas_codec);
            break;
          }
          case 18: {
            npcs_.AddEntriesFrom(input, _repeated_npcs_codec);
            break;
          }
          case 26: {
            resourceFiles_.AddEntriesFrom(input, _repeated_resourceFiles_codec);
            break;
          }
          case 34: {
            if (topLeftTileCoordinate_ == null) {
              TopLeftTileCoordinate = new global::Tibia.Protobuf.Shared.Coordinate();
            }
            input.ReadMessage(TopLeftTileCoordinate);
            break;
          }
          case 42: {
            if (bottomRightTileCoordinate_ == null) {
              BottomRightTileCoordinate = new global::Tibia.Protobuf.Shared.Coordinate();
            }
            input.ReadMessage(BottomRightTileCoordinate);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            areas_.AddEntriesFrom(ref input, _repeated_areas_codec);
            break;
          }
          case 18: {
            npcs_.AddEntriesFrom(ref input, _repeated_npcs_codec);
            break;
          }
          case 26: {
            resourceFiles_.AddEntriesFrom(ref input, _repeated_resourceFiles_codec);
            break;
          }
          case 34: {
            if (topLeftTileCoordinate_ == null) {
              TopLeftTileCoordinate = new global::Tibia.Protobuf.Shared.Coordinate();
            }
            input.ReadMessage(TopLeftTileCoordinate);
            break;
          }
          case 42: {
            if (bottomRightTileCoordinate_ == null) {
              BottomRightTileCoordinate = new global::Tibia.Protobuf.Shared.Coordinate();
            }
            input.ReadMessage(BottomRightTileCoordinate);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Area : pb::IMessage<Area>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Area> _parser = new pb::MessageParser<Area>(() => new Area());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Area> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tibia.Protobuf.Map.MapReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Area() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Area(Area other) : this() {
      _hasBits0 = other._hasBits0;
      areaId_ = other.areaId_;
      name_ = other.name_;
      areaType_ = other.areaType_;
      subareaIds_ = other.subareaIds_.Clone();
      labelCoordinate_ = other.labelCoordinate_ != null ? other.labelCoordinate_.Clone() : null;
      rejectDonations_ = other.rejectDonations_;
      alias_ = other.alias_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Area Clone() {
      return new Area(this);
    }

    /// <summary>Field number for the "area_id" field.</summary>
    public const int AreaIdFieldNumber = 1;
    private readonly static uint AreaIdDefaultValue = 0;

    private uint areaId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AreaId {
      get { if ((_hasBits0 & 1) != 0) { return areaId_; } else { return AreaIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        areaId_ = value;
      }
    }
    /// <summary>Gets whether the "area_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAreaId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "area_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAreaId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private readonly static string NameDefaultValue = "";

    private string name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_ ?? NameDefaultValue; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "area_type" field.</summary>
    public const int AreaTypeFieldNumber = 3;
    private readonly static global::Tibia.Protobuf.Map.AREA_TYPE AreaTypeDefaultValue = global::Tibia.Protobuf.Map.AREA_TYPE.None;

    private global::Tibia.Protobuf.Map.AREA_TYPE areaType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tibia.Protobuf.Map.AREA_TYPE AreaType {
      get { if ((_hasBits0 & 2) != 0) { return areaType_; } else { return AreaTypeDefaultValue; } }
      set {
        _hasBits0 |= 2;
        areaType_ = value;
      }
    }
    /// <summary>Gets whether the "area_type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAreaType {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "area_type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAreaType() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "subarea_ids" field.</summary>
    public const int SubareaIdsFieldNumber = 4;
    private static readonly pb::FieldCodec<uint> _repeated_subareaIds_codec
        = pb::FieldCodec.ForUInt32(32);
    private readonly pbc::RepeatedField<uint> subareaIds_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> SubareaIds {
      get { return subareaIds_; }
    }

    /// <summary>Field number for the "label_coordinate" field.</summary>
    public const int LabelCoordinateFieldNumber = 5;
    private global::Tibia.Protobuf.Shared.Coordinate labelCoordinate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tibia.Protobuf.Shared.Coordinate LabelCoordinate {
      get { return labelCoordinate_; }
      set {
        labelCoordinate_ = value;
      }
    }

    /// <summary>Field number for the "reject_donations" field.</summary>
    public const int RejectDonationsFieldNumber = 6;
    private readonly static bool RejectDonationsDefaultValue = false;

    private bool rejectDonations_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool RejectDonations {
      get { if ((_hasBits0 & 4) != 0) { return rejectDonations_; } else { return RejectDonationsDefaultValue; } }
      set {
        _hasBits0 |= 4;
        rejectDonations_ = value;
      }
    }
    /// <summary>Gets whether the "reject_donations" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRejectDonations {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "reject_donations" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRejectDonations() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "alias" field.</summary>
    public const int AliasFieldNumber = 7;
    private readonly static string AliasDefaultValue = "";

    private string alias_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Alias {
      get { return alias_ ?? AliasDefaultValue; }
      set {
        alias_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "alias" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAlias {
      get { return alias_ != null; }
    }
    /// <summary>Clears the value of the "alias" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAlias() {
      alias_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Area);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Area other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AreaId != other.AreaId) return false;
      if (Name != other.Name) return false;
      if (AreaType != other.AreaType) return false;
      if(!subareaIds_.Equals(other.subareaIds_)) return false;
      if (!object.Equals(LabelCoordinate, other.LabelCoordinate)) return false;
      if (RejectDonations != other.RejectDonations) return false;
      if (Alias != other.Alias) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasAreaId) hash ^= AreaId.GetHashCode();
      if (HasName) hash ^= Name.GetHashCode();
      if (HasAreaType) hash ^= AreaType.GetHashCode();
      hash ^= subareaIds_.GetHashCode();
      if (labelCoordinate_ != null) hash ^= LabelCoordinate.GetHashCode();
      if (HasRejectDonations) hash ^= RejectDonations.GetHashCode();
      if (HasAlias) hash ^= Alias.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasAreaId) {
        output.WriteRawTag(8);
        output.WriteUInt32(AreaId);
      }
      if (HasName) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (HasAreaType) {
        output.WriteRawTag(24);
        output.WriteEnum((int) AreaType);
      }
      subareaIds_.WriteTo(output, _repeated_subareaIds_codec);
      if (labelCoordinate_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(LabelCoordinate);
      }
      if (HasRejectDonations) {
        output.WriteRawTag(48);
        output.WriteBool(RejectDonations);
      }
      if (HasAlias) {
        output.WriteRawTag(58);
        output.WriteString(Alias);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasAreaId) {
        output.WriteRawTag(8);
        output.WriteUInt32(AreaId);
      }
      if (HasName) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (HasAreaType) {
        output.WriteRawTag(24);
        output.WriteEnum((int) AreaType);
      }
      subareaIds_.WriteTo(ref output, _repeated_subareaIds_codec);
      if (labelCoordinate_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(LabelCoordinate);
      }
      if (HasRejectDonations) {
        output.WriteRawTag(48);
        output.WriteBool(RejectDonations);
      }
      if (HasAlias) {
        output.WriteRawTag(58);
        output.WriteString(Alias);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasAreaId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AreaId);
      }
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (HasAreaType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AreaType);
      }
      size += subareaIds_.CalculateSize(_repeated_subareaIds_codec);
      if (labelCoordinate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LabelCoordinate);
      }
      if (HasRejectDonations) {
        size += 1 + 1;
      }
      if (HasAlias) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Alias);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Area other) {
      if (other == null) {
        return;
      }
      if (other.HasAreaId) {
        AreaId = other.AreaId;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasAreaType) {
        AreaType = other.AreaType;
      }
      subareaIds_.Add(other.subareaIds_);
      if (other.labelCoordinate_ != null) {
        if (labelCoordinate_ == null) {
          LabelCoordinate = new global::Tibia.Protobuf.Shared.Coordinate();
        }
        LabelCoordinate.MergeFrom(other.LabelCoordinate);
      }
      if (other.HasRejectDonations) {
        RejectDonations = other.RejectDonations;
      }
      if (other.HasAlias) {
        Alias = other.Alias;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AreaId = input.ReadUInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            AreaType = (global::Tibia.Protobuf.Map.AREA_TYPE) input.ReadEnum();
            break;
          }
          case 34:
          case 32: {
            subareaIds_.AddEntriesFrom(input, _repeated_subareaIds_codec);
            break;
          }
          case 42: {
            if (labelCoordinate_ == null) {
              LabelCoordinate = new global::Tibia.Protobuf.Shared.Coordinate();
            }
            input.ReadMessage(LabelCoordinate);
            break;
          }
          case 48: {
            RejectDonations = input.ReadBool();
            break;
          }
          case 58: {
            Alias = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AreaId = input.ReadUInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            AreaType = (global::Tibia.Protobuf.Map.AREA_TYPE) input.ReadEnum();
            break;
          }
          case 34:
          case 32: {
            subareaIds_.AddEntriesFrom(ref input, _repeated_subareaIds_codec);
            break;
          }
          case 42: {
            if (labelCoordinate_ == null) {
              LabelCoordinate = new global::Tibia.Protobuf.Shared.Coordinate();
            }
            input.ReadMessage(LabelCoordinate);
            break;
          }
          case 48: {
            RejectDonations = input.ReadBool();
            break;
          }
          case 58: {
            Alias = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Npc : pb::IMessage<Npc>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Npc> _parser = new pb::MessageParser<Npc>(() => new Npc());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Npc> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tibia.Protobuf.Map.MapReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Npc() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Npc(Npc other) : this() {
      _hasBits0 = other._hasBits0;
      name_ = other.name_;
      tileCoordinate_ = other.tileCoordinate_ != null ? other.tileCoordinate_.Clone() : null;
      subareaId_ = other.subareaId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Npc Clone() {
      return new Npc(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private readonly static string NameDefaultValue = "";

    private string name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_ ?? NameDefaultValue; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "tile_coordinate" field.</summary>
    public const int TileCoordinateFieldNumber = 2;
    private global::Tibia.Protobuf.Shared.Coordinate tileCoordinate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tibia.Protobuf.Shared.Coordinate TileCoordinate {
      get { return tileCoordinate_; }
      set {
        tileCoordinate_ = value;
      }
    }

    /// <summary>Field number for the "subarea_id" field.</summary>
    public const int SubareaIdFieldNumber = 3;
    private readonly static uint SubareaIdDefaultValue = 0;

    private uint subareaId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SubareaId {
      get { if ((_hasBits0 & 1) != 0) { return subareaId_; } else { return SubareaIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        subareaId_ = value;
      }
    }
    /// <summary>Gets whether the "subarea_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSubareaId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "subarea_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSubareaId() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Npc);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Npc other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!object.Equals(TileCoordinate, other.TileCoordinate)) return false;
      if (SubareaId != other.SubareaId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasName) hash ^= Name.GetHashCode();
      if (tileCoordinate_ != null) hash ^= TileCoordinate.GetHashCode();
      if (HasSubareaId) hash ^= SubareaId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasName) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (tileCoordinate_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TileCoordinate);
      }
      if (HasSubareaId) {
        output.WriteRawTag(24);
        output.WriteUInt32(SubareaId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasName) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (tileCoordinate_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TileCoordinate);
      }
      if (HasSubareaId) {
        output.WriteRawTag(24);
        output.WriteUInt32(SubareaId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (tileCoordinate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TileCoordinate);
      }
      if (HasSubareaId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SubareaId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Npc other) {
      if (other == null) {
        return;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.tileCoordinate_ != null) {
        if (tileCoordinate_ == null) {
          TileCoordinate = new global::Tibia.Protobuf.Shared.Coordinate();
        }
        TileCoordinate.MergeFrom(other.TileCoordinate);
      }
      if (other.HasSubareaId) {
        SubareaId = other.SubareaId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (tileCoordinate_ == null) {
              TileCoordinate = new global::Tibia.Protobuf.Shared.Coordinate();
            }
            input.ReadMessage(TileCoordinate);
            break;
          }
          case 24: {
            SubareaId = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (tileCoordinate_ == null) {
              TileCoordinate = new global::Tibia.Protobuf.Shared.Coordinate();
            }
            input.ReadMessage(TileCoordinate);
            break;
          }
          case 24: {
            SubareaId = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MapFile : pb::IMessage<MapFile>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MapFile> _parser = new pb::MessageParser<MapFile>(() => new MapFile());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MapFile> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tibia.Protobuf.Map.MapReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MapFile() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MapFile(MapFile other) : this() {
      _hasBits0 = other._hasBits0;
      fileType_ = other.fileType_;
      topLeftCoordinate_ = other.topLeftCoordinate_ != null ? other.topLeftCoordinate_.Clone() : null;
      fileName_ = other.fileName_;
      fieldsWidth_ = other.fieldsWidth_;
      fieldsHeight_ = other.fieldsHeight_;
      areaId_ = other.areaId_;
      scaleFactor_ = other.scaleFactor_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MapFile Clone() {
      return new MapFile(this);
    }

    /// <summary>Field number for the "file_type" field.</summary>
    public const int FileTypeFieldNumber = 1;
    private readonly static global::Tibia.Protobuf.Map.MAP_FILE_TYPE FileTypeDefaultValue = global::Tibia.Protobuf.Map.MAP_FILE_TYPE.Subarea;

    private global::Tibia.Protobuf.Map.MAP_FILE_TYPE fileType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tibia.Protobuf.Map.MAP_FILE_TYPE FileType {
      get { if ((_hasBits0 & 1) != 0) { return fileType_; } else { return FileTypeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        fileType_ = value;
      }
    }
    /// <summary>Gets whether the "file_type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFileType {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "file_type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFileType() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "top_left_coordinate" field.</summary>
    public const int TopLeftCoordinateFieldNumber = 2;
    private global::Tibia.Protobuf.Shared.Coordinate topLeftCoordinate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tibia.Protobuf.Shared.Coordinate TopLeftCoordinate {
      get { return topLeftCoordinate_; }
      set {
        topLeftCoordinate_ = value;
      }
    }

    /// <summary>Field number for the "file_name" field.</summary>
    public const int FileNameFieldNumber = 3;
    private readonly static string FileNameDefaultValue = "";

    private string fileName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FileName {
      get { return fileName_ ?? FileNameDefaultValue; }
      set {
        fileName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "file_name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFileName {
      get { return fileName_ != null; }
    }
    /// <summary>Clears the value of the "file_name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFileName() {
      fileName_ = null;
    }

    /// <summary>Field number for the "fields_width" field.</summary>
    public const int FieldsWidthFieldNumber = 4;
    private readonly static uint FieldsWidthDefaultValue = 0;

    private uint fieldsWidth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FieldsWidth {
      get { if ((_hasBits0 & 2) != 0) { return fieldsWidth_; } else { return FieldsWidthDefaultValue; } }
      set {
        _hasBits0 |= 2;
        fieldsWidth_ = value;
      }
    }
    /// <summary>Gets whether the "fields_width" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFieldsWidth {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "fields_width" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFieldsWidth() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "fields_height" field.</summary>
    public const int FieldsHeightFieldNumber = 5;
    private readonly static uint FieldsHeightDefaultValue = 0;

    private uint fieldsHeight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FieldsHeight {
      get { if ((_hasBits0 & 4) != 0) { return fieldsHeight_; } else { return FieldsHeightDefaultValue; } }
      set {
        _hasBits0 |= 4;
        fieldsHeight_ = value;
      }
    }
    /// <summary>Gets whether the "fields_height" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFieldsHeight {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "fields_height" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFieldsHeight() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "area_id" field.</summary>
    public const int AreaIdFieldNumber = 6;
    private readonly static uint AreaIdDefaultValue = 0;

    private uint areaId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AreaId {
      get { if ((_hasBits0 & 8) != 0) { return areaId_; } else { return AreaIdDefaultValue; } }
      set {
        _hasBits0 |= 8;
        areaId_ = value;
      }
    }
    /// <summary>Gets whether the "area_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAreaId {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "area_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAreaId() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "scale_factor" field.</summary>
    public const int ScaleFactorFieldNumber = 7;
    private readonly static double ScaleFactorDefaultValue = 0D;

    private double scaleFactor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double ScaleFactor {
      get { if ((_hasBits0 & 16) != 0) { return scaleFactor_; } else { return ScaleFactorDefaultValue; } }
      set {
        _hasBits0 |= 16;
        scaleFactor_ = value;
      }
    }
    /// <summary>Gets whether the "scale_factor" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasScaleFactor {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "scale_factor" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearScaleFactor() {
      _hasBits0 &= ~16;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MapFile);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MapFile other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FileType != other.FileType) return false;
      if (!object.Equals(TopLeftCoordinate, other.TopLeftCoordinate)) return false;
      if (FileName != other.FileName) return false;
      if (FieldsWidth != other.FieldsWidth) return false;
      if (FieldsHeight != other.FieldsHeight) return false;
      if (AreaId != other.AreaId) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(ScaleFactor, other.ScaleFactor)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasFileType) hash ^= FileType.GetHashCode();
      if (topLeftCoordinate_ != null) hash ^= TopLeftCoordinate.GetHashCode();
      if (HasFileName) hash ^= FileName.GetHashCode();
      if (HasFieldsWidth) hash ^= FieldsWidth.GetHashCode();
      if (HasFieldsHeight) hash ^= FieldsHeight.GetHashCode();
      if (HasAreaId) hash ^= AreaId.GetHashCode();
      if (HasScaleFactor) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(ScaleFactor);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasFileType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) FileType);
      }
      if (topLeftCoordinate_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TopLeftCoordinate);
      }
      if (HasFileName) {
        output.WriteRawTag(26);
        output.WriteString(FileName);
      }
      if (HasFieldsWidth) {
        output.WriteRawTag(32);
        output.WriteUInt32(FieldsWidth);
      }
      if (HasFieldsHeight) {
        output.WriteRawTag(40);
        output.WriteUInt32(FieldsHeight);
      }
      if (HasAreaId) {
        output.WriteRawTag(48);
        output.WriteUInt32(AreaId);
      }
      if (HasScaleFactor) {
        output.WriteRawTag(57);
        output.WriteDouble(ScaleFactor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasFileType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) FileType);
      }
      if (topLeftCoordinate_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TopLeftCoordinate);
      }
      if (HasFileName) {
        output.WriteRawTag(26);
        output.WriteString(FileName);
      }
      if (HasFieldsWidth) {
        output.WriteRawTag(32);
        output.WriteUInt32(FieldsWidth);
      }
      if (HasFieldsHeight) {
        output.WriteRawTag(40);
        output.WriteUInt32(FieldsHeight);
      }
      if (HasAreaId) {
        output.WriteRawTag(48);
        output.WriteUInt32(AreaId);
      }
      if (HasScaleFactor) {
        output.WriteRawTag(57);
        output.WriteDouble(ScaleFactor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasFileType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) FileType);
      }
      if (topLeftCoordinate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TopLeftCoordinate);
      }
      if (HasFileName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FileName);
      }
      if (HasFieldsWidth) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FieldsWidth);
      }
      if (HasFieldsHeight) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FieldsHeight);
      }
      if (HasAreaId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AreaId);
      }
      if (HasScaleFactor) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MapFile other) {
      if (other == null) {
        return;
      }
      if (other.HasFileType) {
        FileType = other.FileType;
      }
      if (other.topLeftCoordinate_ != null) {
        if (topLeftCoordinate_ == null) {
          TopLeftCoordinate = new global::Tibia.Protobuf.Shared.Coordinate();
        }
        TopLeftCoordinate.MergeFrom(other.TopLeftCoordinate);
      }
      if (other.HasFileName) {
        FileName = other.FileName;
      }
      if (other.HasFieldsWidth) {
        FieldsWidth = other.FieldsWidth;
      }
      if (other.HasFieldsHeight) {
        FieldsHeight = other.FieldsHeight;
      }
      if (other.HasAreaId) {
        AreaId = other.AreaId;
      }
      if (other.HasScaleFactor) {
        ScaleFactor = other.ScaleFactor;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FileType = (global::Tibia.Protobuf.Map.MAP_FILE_TYPE) input.ReadEnum();
            break;
          }
          case 18: {
            if (topLeftCoordinate_ == null) {
              TopLeftCoordinate = new global::Tibia.Protobuf.Shared.Coordinate();
            }
            input.ReadMessage(TopLeftCoordinate);
            break;
          }
          case 26: {
            FileName = input.ReadString();
            break;
          }
          case 32: {
            FieldsWidth = input.ReadUInt32();
            break;
          }
          case 40: {
            FieldsHeight = input.ReadUInt32();
            break;
          }
          case 48: {
            AreaId = input.ReadUInt32();
            break;
          }
          case 57: {
            ScaleFactor = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            FileType = (global::Tibia.Protobuf.Map.MAP_FILE_TYPE) input.ReadEnum();
            break;
          }
          case 18: {
            if (topLeftCoordinate_ == null) {
              TopLeftCoordinate = new global::Tibia.Protobuf.Shared.Coordinate();
            }
            input.ReadMessage(TopLeftCoordinate);
            break;
          }
          case 26: {
            FileName = input.ReadString();
            break;
          }
          case 32: {
            FieldsWidth = input.ReadUInt32();
            break;
          }
          case 40: {
            FieldsHeight = input.ReadUInt32();
            break;
          }
          case 48: {
            AreaId = input.ReadUInt32();
            break;
          }
          case 57: {
            ScaleFactor = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
