// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: staticdata.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tibia.Protobuf.Staticdata {

  /// <summary>Holder for reflection information generated from staticdata.proto</summary>
  public static partial class StaticdataReflection {

    #region Descriptor
    /// <summary>File descriptor for staticdata.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StaticdataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBzdGF0aWNkYXRhLnByb3RvEhl0aWJpYS5wcm90b2J1Zi5zdGF0aWNkYXRh",
            "In8KClN0YXRpY0RhdGESMwoHbW9uc3RlchgBIAMoCzIiLnRpYmlhLnByb3Rv",
            "YnVmLnN0YXRpY2RhdGEuTW9uc3RlchI8CgxhY2hpZXZlbWVudHMYAiADKAsy",
            "Ji50aWJpYS5wcm90b2J1Zi5zdGF0aWNkYXRhLkFjaGlldmVtZW50IqEBCgZP",
            "dXRmaXQSEQoJb3V0Zml0X2lkGAEgASgNEhIKCmhlYWRfY29sb3IYAiABKA0S",
            "EwoLdG9yc29fY29sb3IYAyABKA0SEgoKbGVnc19jb2xvchgEIAEoDRIUCgxk",
            "ZXRhaWxfY29sb3IYBSABKA0SDgoGYWRkb25zGAYgASgNEiEKGW9iamVjdF9h",
            "cHBlYXJhbmNlX3R5cGVfaWQYByABKA0iWAoHTW9uc3RlchIMCgRyYWNlGAEg",
            "ASgNEgwKBG5hbWUYAiABKAkSMQoGb3V0Zml0GAMgASgLMiEudGliaWEucHJv",
            "dG9idWYuc3RhdGljZGF0YS5PdXRmaXQiVwoLQWNoaWV2ZW1lbnQSFgoOYWNo",
            "aWV2ZW1lbnRfaWQYASABKA0SDAoEbmFtZRgCIAEoCRITCgtkZXNjcmlwdGlv",
            "bhgDIAEoCRINCgVncmFkZRgEIAEoDQ=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Tibia.Protobuf.Staticdata.StaticData), global::Tibia.Protobuf.Staticdata.StaticData.Parser, new[]{ "Monster", "Achievements" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Tibia.Protobuf.Staticdata.Outfit), global::Tibia.Protobuf.Staticdata.Outfit.Parser, new[]{ "OutfitId", "HeadColor", "TorsoColor", "LegsColor", "DetailColor", "Addons", "ObjectAppearanceTypeId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Tibia.Protobuf.Staticdata.Monster), global::Tibia.Protobuf.Staticdata.Monster.Parser, new[]{ "Race", "Name", "Outfit" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Tibia.Protobuf.Staticdata.Achievement), global::Tibia.Protobuf.Staticdata.Achievement.Parser, new[]{ "AchievementId", "Name", "Description", "Grade" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class StaticData : pb::IMessage<StaticData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StaticData> _parser = new pb::MessageParser<StaticData>(() => new StaticData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<StaticData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tibia.Protobuf.Staticdata.StaticdataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StaticData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StaticData(StaticData other) : this() {
      monster_ = other.monster_.Clone();
      achievements_ = other.achievements_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StaticData Clone() {
      return new StaticData(this);
    }

    /// <summary>Field number for the "monster" field.</summary>
    public const int MonsterFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Tibia.Protobuf.Staticdata.Monster> _repeated_monster_codec
        = pb::FieldCodec.ForMessage(10, global::Tibia.Protobuf.Staticdata.Monster.Parser);
    private readonly pbc::RepeatedField<global::Tibia.Protobuf.Staticdata.Monster> monster_ = new pbc::RepeatedField<global::Tibia.Protobuf.Staticdata.Monster>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Tibia.Protobuf.Staticdata.Monster> Monster {
      get { return monster_; }
    }

    /// <summary>Field number for the "achievements" field.</summary>
    public const int AchievementsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Tibia.Protobuf.Staticdata.Achievement> _repeated_achievements_codec
        = pb::FieldCodec.ForMessage(18, global::Tibia.Protobuf.Staticdata.Achievement.Parser);
    private readonly pbc::RepeatedField<global::Tibia.Protobuf.Staticdata.Achievement> achievements_ = new pbc::RepeatedField<global::Tibia.Protobuf.Staticdata.Achievement>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Tibia.Protobuf.Staticdata.Achievement> Achievements {
      get { return achievements_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as StaticData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(StaticData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!monster_.Equals(other.monster_)) return false;
      if(!achievements_.Equals(other.achievements_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= monster_.GetHashCode();
      hash ^= achievements_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      monster_.WriteTo(output, _repeated_monster_codec);
      achievements_.WriteTo(output, _repeated_achievements_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      monster_.WriteTo(ref output, _repeated_monster_codec);
      achievements_.WriteTo(ref output, _repeated_achievements_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += monster_.CalculateSize(_repeated_monster_codec);
      size += achievements_.CalculateSize(_repeated_achievements_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(StaticData other) {
      if (other == null) {
        return;
      }
      monster_.Add(other.monster_);
      achievements_.Add(other.achievements_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            monster_.AddEntriesFrom(input, _repeated_monster_codec);
            break;
          }
          case 18: {
            achievements_.AddEntriesFrom(input, _repeated_achievements_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            monster_.AddEntriesFrom(ref input, _repeated_monster_codec);
            break;
          }
          case 18: {
            achievements_.AddEntriesFrom(ref input, _repeated_achievements_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Outfit : pb::IMessage<Outfit>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Outfit> _parser = new pb::MessageParser<Outfit>(() => new Outfit());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Outfit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tibia.Protobuf.Staticdata.StaticdataReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Outfit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Outfit(Outfit other) : this() {
      _hasBits0 = other._hasBits0;
      outfitId_ = other.outfitId_;
      headColor_ = other.headColor_;
      torsoColor_ = other.torsoColor_;
      legsColor_ = other.legsColor_;
      detailColor_ = other.detailColor_;
      addons_ = other.addons_;
      objectAppearanceTypeId_ = other.objectAppearanceTypeId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Outfit Clone() {
      return new Outfit(this);
    }

    /// <summary>Field number for the "outfit_id" field.</summary>
    public const int OutfitIdFieldNumber = 1;
    private readonly static uint OutfitIdDefaultValue = 0;

    private uint outfitId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint OutfitId {
      get { if ((_hasBits0 & 1) != 0) { return outfitId_; } else { return OutfitIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        outfitId_ = value;
      }
    }
    /// <summary>Gets whether the "outfit_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOutfitId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "outfit_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOutfitId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "head_color" field.</summary>
    public const int HeadColorFieldNumber = 2;
    private readonly static uint HeadColorDefaultValue = 0;

    private uint headColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint HeadColor {
      get { if ((_hasBits0 & 2) != 0) { return headColor_; } else { return HeadColorDefaultValue; } }
      set {
        _hasBits0 |= 2;
        headColor_ = value;
      }
    }
    /// <summary>Gets whether the "head_color" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasHeadColor {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "head_color" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearHeadColor() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "torso_color" field.</summary>
    public const int TorsoColorFieldNumber = 3;
    private readonly static uint TorsoColorDefaultValue = 0;

    private uint torsoColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TorsoColor {
      get { if ((_hasBits0 & 4) != 0) { return torsoColor_; } else { return TorsoColorDefaultValue; } }
      set {
        _hasBits0 |= 4;
        torsoColor_ = value;
      }
    }
    /// <summary>Gets whether the "torso_color" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTorsoColor {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "torso_color" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTorsoColor() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "legs_color" field.</summary>
    public const int LegsColorFieldNumber = 4;
    private readonly static uint LegsColorDefaultValue = 0;

    private uint legsColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LegsColor {
      get { if ((_hasBits0 & 8) != 0) { return legsColor_; } else { return LegsColorDefaultValue; } }
      set {
        _hasBits0 |= 8;
        legsColor_ = value;
      }
    }
    /// <summary>Gets whether the "legs_color" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLegsColor {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "legs_color" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLegsColor() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "detail_color" field.</summary>
    public const int DetailColorFieldNumber = 5;
    private readonly static uint DetailColorDefaultValue = 0;

    private uint detailColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DetailColor {
      get { if ((_hasBits0 & 16) != 0) { return detailColor_; } else { return DetailColorDefaultValue; } }
      set {
        _hasBits0 |= 16;
        detailColor_ = value;
      }
    }
    /// <summary>Gets whether the "detail_color" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDetailColor {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "detail_color" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDetailColor() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "addons" field.</summary>
    public const int AddonsFieldNumber = 6;
    private readonly static uint AddonsDefaultValue = 0;

    private uint addons_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Addons {
      get { if ((_hasBits0 & 32) != 0) { return addons_; } else { return AddonsDefaultValue; } }
      set {
        _hasBits0 |= 32;
        addons_ = value;
      }
    }
    /// <summary>Gets whether the "addons" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAddons {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "addons" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAddons() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "object_appearance_type_id" field.</summary>
    public const int ObjectAppearanceTypeIdFieldNumber = 7;
    private readonly static uint ObjectAppearanceTypeIdDefaultValue = 0;

    private uint objectAppearanceTypeId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ObjectAppearanceTypeId {
      get { if ((_hasBits0 & 64) != 0) { return objectAppearanceTypeId_; } else { return ObjectAppearanceTypeIdDefaultValue; } }
      set {
        _hasBits0 |= 64;
        objectAppearanceTypeId_ = value;
      }
    }
    /// <summary>Gets whether the "object_appearance_type_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasObjectAppearanceTypeId {
      get { return (_hasBits0 & 64) != 0; }
    }
    /// <summary>Clears the value of the "object_appearance_type_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearObjectAppearanceTypeId() {
      _hasBits0 &= ~64;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Outfit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Outfit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OutfitId != other.OutfitId) return false;
      if (HeadColor != other.HeadColor) return false;
      if (TorsoColor != other.TorsoColor) return false;
      if (LegsColor != other.LegsColor) return false;
      if (DetailColor != other.DetailColor) return false;
      if (Addons != other.Addons) return false;
      if (ObjectAppearanceTypeId != other.ObjectAppearanceTypeId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasOutfitId) hash ^= OutfitId.GetHashCode();
      if (HasHeadColor) hash ^= HeadColor.GetHashCode();
      if (HasTorsoColor) hash ^= TorsoColor.GetHashCode();
      if (HasLegsColor) hash ^= LegsColor.GetHashCode();
      if (HasDetailColor) hash ^= DetailColor.GetHashCode();
      if (HasAddons) hash ^= Addons.GetHashCode();
      if (HasObjectAppearanceTypeId) hash ^= ObjectAppearanceTypeId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasOutfitId) {
        output.WriteRawTag(8);
        output.WriteUInt32(OutfitId);
      }
      if (HasHeadColor) {
        output.WriteRawTag(16);
        output.WriteUInt32(HeadColor);
      }
      if (HasTorsoColor) {
        output.WriteRawTag(24);
        output.WriteUInt32(TorsoColor);
      }
      if (HasLegsColor) {
        output.WriteRawTag(32);
        output.WriteUInt32(LegsColor);
      }
      if (HasDetailColor) {
        output.WriteRawTag(40);
        output.WriteUInt32(DetailColor);
      }
      if (HasAddons) {
        output.WriteRawTag(48);
        output.WriteUInt32(Addons);
      }
      if (HasObjectAppearanceTypeId) {
        output.WriteRawTag(56);
        output.WriteUInt32(ObjectAppearanceTypeId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasOutfitId) {
        output.WriteRawTag(8);
        output.WriteUInt32(OutfitId);
      }
      if (HasHeadColor) {
        output.WriteRawTag(16);
        output.WriteUInt32(HeadColor);
      }
      if (HasTorsoColor) {
        output.WriteRawTag(24);
        output.WriteUInt32(TorsoColor);
      }
      if (HasLegsColor) {
        output.WriteRawTag(32);
        output.WriteUInt32(LegsColor);
      }
      if (HasDetailColor) {
        output.WriteRawTag(40);
        output.WriteUInt32(DetailColor);
      }
      if (HasAddons) {
        output.WriteRawTag(48);
        output.WriteUInt32(Addons);
      }
      if (HasObjectAppearanceTypeId) {
        output.WriteRawTag(56);
        output.WriteUInt32(ObjectAppearanceTypeId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasOutfitId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(OutfitId);
      }
      if (HasHeadColor) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HeadColor);
      }
      if (HasTorsoColor) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TorsoColor);
      }
      if (HasLegsColor) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LegsColor);
      }
      if (HasDetailColor) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DetailColor);
      }
      if (HasAddons) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Addons);
      }
      if (HasObjectAppearanceTypeId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ObjectAppearanceTypeId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Outfit other) {
      if (other == null) {
        return;
      }
      if (other.HasOutfitId) {
        OutfitId = other.OutfitId;
      }
      if (other.HasHeadColor) {
        HeadColor = other.HeadColor;
      }
      if (other.HasTorsoColor) {
        TorsoColor = other.TorsoColor;
      }
      if (other.HasLegsColor) {
        LegsColor = other.LegsColor;
      }
      if (other.HasDetailColor) {
        DetailColor = other.DetailColor;
      }
      if (other.HasAddons) {
        Addons = other.Addons;
      }
      if (other.HasObjectAppearanceTypeId) {
        ObjectAppearanceTypeId = other.ObjectAppearanceTypeId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OutfitId = input.ReadUInt32();
            break;
          }
          case 16: {
            HeadColor = input.ReadUInt32();
            break;
          }
          case 24: {
            TorsoColor = input.ReadUInt32();
            break;
          }
          case 32: {
            LegsColor = input.ReadUInt32();
            break;
          }
          case 40: {
            DetailColor = input.ReadUInt32();
            break;
          }
          case 48: {
            Addons = input.ReadUInt32();
            break;
          }
          case 56: {
            ObjectAppearanceTypeId = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            OutfitId = input.ReadUInt32();
            break;
          }
          case 16: {
            HeadColor = input.ReadUInt32();
            break;
          }
          case 24: {
            TorsoColor = input.ReadUInt32();
            break;
          }
          case 32: {
            LegsColor = input.ReadUInt32();
            break;
          }
          case 40: {
            DetailColor = input.ReadUInt32();
            break;
          }
          case 48: {
            Addons = input.ReadUInt32();
            break;
          }
          case 56: {
            ObjectAppearanceTypeId = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Monster : pb::IMessage<Monster>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Monster> _parser = new pb::MessageParser<Monster>(() => new Monster());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Monster> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tibia.Protobuf.Staticdata.StaticdataReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Monster() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Monster(Monster other) : this() {
      _hasBits0 = other._hasBits0;
      race_ = other.race_;
      name_ = other.name_;
      outfit_ = other.outfit_ != null ? other.outfit_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Monster Clone() {
      return new Monster(this);
    }

    /// <summary>Field number for the "race" field.</summary>
    public const int RaceFieldNumber = 1;
    private readonly static uint RaceDefaultValue = 0;

    private uint race_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Race {
      get { if ((_hasBits0 & 1) != 0) { return race_; } else { return RaceDefaultValue; } }
      set {
        _hasBits0 |= 1;
        race_ = value;
      }
    }
    /// <summary>Gets whether the "race" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRace {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "race" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRace() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private readonly static string NameDefaultValue = "";

    private string name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_ ?? NameDefaultValue; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "outfit" field.</summary>
    public const int OutfitFieldNumber = 3;
    private global::Tibia.Protobuf.Staticdata.Outfit outfit_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tibia.Protobuf.Staticdata.Outfit Outfit {
      get { return outfit_; }
      set {
        outfit_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Monster);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Monster other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Race != other.Race) return false;
      if (Name != other.Name) return false;
      if (!object.Equals(Outfit, other.Outfit)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasRace) hash ^= Race.GetHashCode();
      if (HasName) hash ^= Name.GetHashCode();
      if (outfit_ != null) hash ^= Outfit.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasRace) {
        output.WriteRawTag(8);
        output.WriteUInt32(Race);
      }
      if (HasName) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (outfit_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Outfit);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasRace) {
        output.WriteRawTag(8);
        output.WriteUInt32(Race);
      }
      if (HasName) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (outfit_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Outfit);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasRace) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Race);
      }
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (outfit_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Outfit);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Monster other) {
      if (other == null) {
        return;
      }
      if (other.HasRace) {
        Race = other.Race;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.outfit_ != null) {
        if (outfit_ == null) {
          Outfit = new global::Tibia.Protobuf.Staticdata.Outfit();
        }
        Outfit.MergeFrom(other.Outfit);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Race = input.ReadUInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            if (outfit_ == null) {
              Outfit = new global::Tibia.Protobuf.Staticdata.Outfit();
            }
            input.ReadMessage(Outfit);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Race = input.ReadUInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            if (outfit_ == null) {
              Outfit = new global::Tibia.Protobuf.Staticdata.Outfit();
            }
            input.ReadMessage(Outfit);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Achievement : pb::IMessage<Achievement>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Achievement> _parser = new pb::MessageParser<Achievement>(() => new Achievement());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Achievement> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tibia.Protobuf.Staticdata.StaticdataReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Achievement() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Achievement(Achievement other) : this() {
      _hasBits0 = other._hasBits0;
      achievementId_ = other.achievementId_;
      name_ = other.name_;
      description_ = other.description_;
      grade_ = other.grade_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Achievement Clone() {
      return new Achievement(this);
    }

    /// <summary>Field number for the "achievement_id" field.</summary>
    public const int AchievementIdFieldNumber = 1;
    private readonly static uint AchievementIdDefaultValue = 0;

    private uint achievementId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AchievementId {
      get { if ((_hasBits0 & 1) != 0) { return achievementId_; } else { return AchievementIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        achievementId_ = value;
      }
    }
    /// <summary>Gets whether the "achievement_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAchievementId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "achievement_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAchievementId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private readonly static string NameDefaultValue = "";

    private string name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_ ?? NameDefaultValue; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 3;
    private readonly static string DescriptionDefaultValue = "";

    private string description_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Description {
      get { return description_ ?? DescriptionDefaultValue; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "description" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDescription {
      get { return description_ != null; }
    }
    /// <summary>Clears the value of the "description" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDescription() {
      description_ = null;
    }

    /// <summary>Field number for the "grade" field.</summary>
    public const int GradeFieldNumber = 4;
    private readonly static uint GradeDefaultValue = 0;

    private uint grade_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Grade {
      get { if ((_hasBits0 & 2) != 0) { return grade_; } else { return GradeDefaultValue; } }
      set {
        _hasBits0 |= 2;
        grade_ = value;
      }
    }
    /// <summary>Gets whether the "grade" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasGrade {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "grade" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearGrade() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Achievement);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Achievement other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AchievementId != other.AchievementId) return false;
      if (Name != other.Name) return false;
      if (Description != other.Description) return false;
      if (Grade != other.Grade) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasAchievementId) hash ^= AchievementId.GetHashCode();
      if (HasName) hash ^= Name.GetHashCode();
      if (HasDescription) hash ^= Description.GetHashCode();
      if (HasGrade) hash ^= Grade.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasAchievementId) {
        output.WriteRawTag(8);
        output.WriteUInt32(AchievementId);
      }
      if (HasName) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (HasDescription) {
        output.WriteRawTag(26);
        output.WriteString(Description);
      }
      if (HasGrade) {
        output.WriteRawTag(32);
        output.WriteUInt32(Grade);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasAchievementId) {
        output.WriteRawTag(8);
        output.WriteUInt32(AchievementId);
      }
      if (HasName) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (HasDescription) {
        output.WriteRawTag(26);
        output.WriteString(Description);
      }
      if (HasGrade) {
        output.WriteRawTag(32);
        output.WriteUInt32(Grade);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasAchievementId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AchievementId);
      }
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (HasDescription) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (HasGrade) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Grade);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Achievement other) {
      if (other == null) {
        return;
      }
      if (other.HasAchievementId) {
        AchievementId = other.AchievementId;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasDescription) {
        Description = other.Description;
      }
      if (other.HasGrade) {
        Grade = other.Grade;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AchievementId = input.ReadUInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Description = input.ReadString();
            break;
          }
          case 32: {
            Grade = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AchievementId = input.ReadUInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Description = input.ReadString();
            break;
          }
          case 32: {
            Grade = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
